name: demo
on: [push]
jobs:
  demo-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Run a test script
        run: echo "Hello World"
      - uses: actions/checkout@v5
      - name: Use node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
      - run: npm install
      - name: Run express app
      - run: node server.js
      - name: Run Jest test
      - run: npm run test
